/**
 * Runtime configuration for the frontend.
 *
 * This module provides access to configuration values that can be set at runtime
 * through Docker environment variables, rather than being embedded at build time.
 *
 * The configuration is injected via /config.js which is generated by the Docker
 * container's entrypoint script from the VITE_API_URL environment variable.
 */

/**
 * Get the API URL, preferring runtime config over build-time env vars.
 */
export function getApiUrl(): string {
  // First check for runtime config (set by Docker entrypoint)
  if (window.__RUNTIME_CONFIG__?.API_URL) {
    return window.__RUNTIME_CONFIG__.API_URL;
  }

  // Fall back to build-time environment variable
  if (import.meta.env.VITE_API_URL) {
    return import.meta.env.VITE_API_URL;
  }

  // Default for local development
  return 'http://localhost:3001';
}

// Export a constant for convenience (evaluated at import time)
// Note: For most cases, use getApiUrl() directly to ensure runtime config is checked
export const API_BASE = getApiUrl();
